// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// BasesColumns holds the columns for the "bases" table.
	BasesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true},
	}
	// BasesTable holds the schema information for the "bases" table.
	BasesTable = &schema.Table{
		Name:       "bases",
		Columns:    BasesColumns,
		PrimaryKey: []*schema.Column{BasesColumns[0]},
	}
	// NodesColumns holds the columns for the "nodes" table.
	NodesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true},
		{Name: "hostname", Type: field.TypeString},
		{Name: "status", Type: field.TypeInt},
	}
	// NodesTable holds the schema information for the "nodes" table.
	NodesTable = &schema.Table{
		Name:       "nodes",
		Columns:    NodesColumns,
		PrimaryKey: []*schema.Column{NodesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "node_hostname_id",
				Unique:  true,
				Columns: []*schema.Column{NodesColumns[3], NodesColumns[0]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		BasesTable,
		NodesTable,
	}
)

func init() {
}
