// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// BaseModel is the predicate function for basemodel builders.
type BaseModel func(*sql.Selector)

// Node is the predicate function for node builders.
type Node func(*sql.Selector)
