// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"gitlab.kylincloud.org/kylincloud/nucleus/src/ent/basemodel"
)

// BaseModelCreate is the builder for creating a BaseModel entity.
type BaseModelCreate struct {
	config
	mutation *BaseModelMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (bmc *BaseModelCreate) SetCreatedAt(t time.Time) *BaseModelCreate {
	bmc.mutation.SetCreatedAt(t)
	return bmc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (bmc *BaseModelCreate) SetNillableCreatedAt(t *time.Time) *BaseModelCreate {
	if t != nil {
		bmc.SetCreatedAt(*t)
	}
	return bmc
}

// SetUpdatedAt sets the "updated_at" field.
func (bmc *BaseModelCreate) SetUpdatedAt(t time.Time) *BaseModelCreate {
	bmc.mutation.SetUpdatedAt(t)
	return bmc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (bmc *BaseModelCreate) SetNillableUpdatedAt(t *time.Time) *BaseModelCreate {
	if t != nil {
		bmc.SetUpdatedAt(*t)
	}
	return bmc
}

// SetID sets the "id" field.
func (bmc *BaseModelCreate) SetID(i int) *BaseModelCreate {
	bmc.mutation.SetID(i)
	return bmc
}

// Mutation returns the BaseModelMutation object of the builder.
func (bmc *BaseModelCreate) Mutation() *BaseModelMutation {
	return bmc.mutation
}

// Save creates the BaseModel in the database.
func (bmc *BaseModelCreate) Save(ctx context.Context) (*BaseModel, error) {
	var (
		err  error
		node *BaseModel
	)
	bmc.defaults()
	if len(bmc.hooks) == 0 {
		if err = bmc.check(); err != nil {
			return nil, err
		}
		node, err = bmc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*BaseModelMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = bmc.check(); err != nil {
				return nil, err
			}
			bmc.mutation = mutation
			if node, err = bmc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(bmc.hooks) - 1; i >= 0; i-- {
			if bmc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = bmc.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, bmc.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*BaseModel)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from BaseModelMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (bmc *BaseModelCreate) SaveX(ctx context.Context) *BaseModel {
	v, err := bmc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (bmc *BaseModelCreate) Exec(ctx context.Context) error {
	_, err := bmc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bmc *BaseModelCreate) ExecX(ctx context.Context) {
	if err := bmc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (bmc *BaseModelCreate) defaults() {
	if _, ok := bmc.mutation.CreatedAt(); !ok {
		v := basemodel.DefaultCreatedAt()
		bmc.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (bmc *BaseModelCreate) check() error {
	if _, ok := bmc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "BaseModel.created_at"`)}
	}
	if v, ok := bmc.mutation.ID(); ok {
		if err := basemodel.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "BaseModel.id": %w`, err)}
		}
	}
	return nil
}

func (bmc *BaseModelCreate) sqlSave(ctx context.Context) (*BaseModel, error) {
	_node, _spec := bmc.createSpec()
	if err := sqlgraph.CreateNode(ctx, bmc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	return _node, nil
}

func (bmc *BaseModelCreate) createSpec() (*BaseModel, *sqlgraph.CreateSpec) {
	var (
		_node = &BaseModel{config: bmc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: basemodel.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: basemodel.FieldID,
			},
		}
	)
	if id, ok := bmc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := bmc.mutation.CreatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: basemodel.FieldCreatedAt,
		})
		_node.CreatedAt = value
	}
	if value, ok := bmc.mutation.UpdatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: basemodel.FieldUpdatedAt,
		})
		_node.UpdatedAt = &value
	}
	return _node, _spec
}

// BaseModelCreateBulk is the builder for creating many BaseModel entities in bulk.
type BaseModelCreateBulk struct {
	config
	builders []*BaseModelCreate
}

// Save creates the BaseModel entities in the database.
func (bmcb *BaseModelCreateBulk) Save(ctx context.Context) ([]*BaseModel, error) {
	specs := make([]*sqlgraph.CreateSpec, len(bmcb.builders))
	nodes := make([]*BaseModel, len(bmcb.builders))
	mutators := make([]Mutator, len(bmcb.builders))
	for i := range bmcb.builders {
		func(i int, root context.Context) {
			builder := bmcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BaseModelMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, bmcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, bmcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, bmcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (bmcb *BaseModelCreateBulk) SaveX(ctx context.Context) []*BaseModel {
	v, err := bmcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (bmcb *BaseModelCreateBulk) Exec(ctx context.Context) error {
	_, err := bmcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bmcb *BaseModelCreateBulk) ExecX(ctx context.Context) {
	if err := bmcb.Exec(ctx); err != nil {
		panic(err)
	}
}
