// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"gitlab.kylincloud.org/kylincloud/nucleus/src/ent/basemodel"
	"gitlab.kylincloud.org/kylincloud/nucleus/src/ent/node"
	"gitlab.kylincloud.org/kylincloud/nucleus/src/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	basemodelFields := schema.BaseModel{}.Fields()
	_ = basemodelFields
	// basemodelDescCreatedAt is the schema descriptor for created_at field.
	basemodelDescCreatedAt := basemodelFields[1].Descriptor()
	// basemodel.DefaultCreatedAt holds the default value on creation for the created_at field.
	basemodel.DefaultCreatedAt = basemodelDescCreatedAt.Default.(func() time.Time)
	// basemodelDescUpdatedAt is the schema descriptor for updated_at field.
	basemodelDescUpdatedAt := basemodelFields[2].Descriptor()
	// basemodel.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	basemodel.UpdateDefaultUpdatedAt = basemodelDescUpdatedAt.UpdateDefault.(func() time.Time)
	// basemodelDescID is the schema descriptor for id field.
	basemodelDescID := basemodelFields[0].Descriptor()
	// basemodel.IDValidator is a validator for the "id" field. It is called by the builders before save.
	basemodel.IDValidator = basemodelDescID.Validators[0].(func(int) error)
	nodeMixin := schema.Node{}.Mixin()
	nodeMixinFields0 := nodeMixin[0].Fields()
	_ = nodeMixinFields0
	nodeFields := schema.Node{}.Fields()
	_ = nodeFields
	// nodeDescCreatedAt is the schema descriptor for created_at field.
	nodeDescCreatedAt := nodeMixinFields0[1].Descriptor()
	// node.DefaultCreatedAt holds the default value on creation for the created_at field.
	node.DefaultCreatedAt = nodeDescCreatedAt.Default.(func() time.Time)
	// nodeDescUpdatedAt is the schema descriptor for updated_at field.
	nodeDescUpdatedAt := nodeMixinFields0[2].Descriptor()
	// node.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	node.UpdateDefaultUpdatedAt = nodeDescUpdatedAt.UpdateDefault.(func() time.Time)
	// nodeDescID is the schema descriptor for id field.
	nodeDescID := nodeFields[0].Descriptor()
	// node.IDValidator is a validator for the "id" field. It is called by the builders before save.
	node.IDValidator = nodeDescID.Validators[0].(func(int) error)
}
